//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JLQ.Common.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JLQ.Common.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap chevrondown {
            get {
                object obj = ResourceManager.GetObject("chevrondown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap chevronleft {
            get {
                object obj = ResourceManager.GetObject("chevronleft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap chevronright {
            get {
                object obj = ResourceManager.GetObject("chevronright", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap chevronup {
            get {
                object obj = ResourceManager.GetObject("chevronup", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap closepanel {
            get {
                object obj = ResourceManager.GetObject("closepanel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 A value indicating whether pressing ENTER in the editable portion of the combo box creates a new line of text in the control or activates the default button for the form. 的本地化字符串。
        /// </summary>
        internal static string MlcbDesc_AcceptsReturn {
            get {
                return ResourceManager.GetString("MlcbDesc_AcceptsReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A value indicating whether pressing the TAB key in the editable portion types a TAB character in the control instead of moving the focus to the next control in the tab order. 的本地化字符串。
        /// </summary>
        internal static string MlcbDesc_AcceptsTab {
            get {
                return ResourceManager.GetString("MlcbDesc_AcceptsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The width of the drop-down button in the combo box. 的本地化字符串。
        /// </summary>
        internal static string MlcbDesc_ButtonWidth {
            get {
                return ResourceManager.GetString("MlcbDesc_ButtonWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The data source for the combo box. 的本地化字符串。
        /// </summary>
        internal static string MlcbDesc_DataSource {
            get {
                return ResourceManager.GetString("MlcbDesc_DataSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Event raised when the DataSource property changed. 的本地化字符串。
        /// </summary>
        internal static string MlcbDesc_DataSourceChanged {
            get {
                return ResourceManager.GetString("MlcbDesc_DataSourceChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The property to display for the combo box. 的本地化字符串。
        /// </summary>
        internal static string MlcbDesc_DisplayMember {
            get {
                return ResourceManager.GetString("MlcbDesc_DisplayMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Event raised when the DisplayMember property changes. 的本地化字符串。
        /// </summary>
        internal static string MlcbDesc_DisplayMemberChanged {
            get {
                return ResourceManager.GetString("MlcbDesc_DisplayMemberChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Occers when a visual aspect of an owner-drawn combo box changes. 的本地化字符串。
        /// </summary>
        internal static string MlcbDesc_DrawItem {
            get {
                return ResourceManager.GetString("MlcbDesc_DrawItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The value indicating whether your code or the operating system will handle drawing of elements in the list. 的本地化字符串。
        /// </summary>
        internal static string MlcbDesc_DrawMode {
            get {
                return ResourceManager.GetString("MlcbDesc_DrawMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Occurs when the drop-down portion of the combo box is shown. 的本地化字符串。
        /// </summary>
        internal static string MlcbDesc_DropDown {
            get {
                return ResourceManager.GetString("MlcbDesc_DropDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The background color for the drop-down portion of the combo box. 的本地化字符串。
        /// </summary>
        internal static string MlcbDesc_DropDownBackColor {
            get {
                return ResourceManager.GetString("MlcbDesc_DropDownBackColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Occurs when the drop-down portion of the combo box is no longer visible. 的本地化字符串。
        /// </summary>
        internal static string MlcbDesc_DropDownClosed {
            get {
                return ResourceManager.GetString("MlcbDesc_DropDownClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The font of the drop-down portion of the combo box. 的本地化字符串。
        /// </summary>
        internal static string MlcbDesc_DropDownFont {
            get {
                return ResourceManager.GetString("MlcbDesc_DropDownFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The foreground color for the drop-down portion of the combo box. 的本地化字符串。
        /// </summary>
        internal static string MlcbDesc_DropDownForeColor {
            get {
                return ResourceManager.GetString("MlcbDesc_DropDownForeColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The height in pixels of the drop-down portion of the combo box. 的本地化字符串。
        /// </summary>
        internal static string MlcbDesc_DropDownHeight {
            get {
                return ResourceManager.GetString("MlcbDesc_DropDownHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A value specifying the style of the combo box. 的本地化字符串。
        /// </summary>
        internal static string MlcbDesc_DropDownStyle {
            get {
                return ResourceManager.GetString("MlcbDesc_DropDownStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Occurs when the DropDownStyle property has changed. 的本地化字符串。
        /// </summary>
        internal static string MlcbDesc_DropDownStyleChanged {
            get {
                return ResourceManager.GetString("MlcbDesc_DropDownStyleChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The width of the drop-down portion of the combo box. 的本地化字符串。
        /// </summary>
        internal static string MlcbDesc_DropDownWidth {
            get {
                return ResourceManager.GetString("MlcbDesc_DropDownWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A value indicating whether the fading effect of the combo box is enabled. 的本地化字符串。
        /// </summary>
        internal static string MlcbDesc_FadeEffect {
            get {
                return ResourceManager.GetString("MlcbDesc_FadeEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Event raised when the control is bound to a data value. 的本地化字符串。
        /// </summary>
        internal static string MlcbDesc_Format {
            get {
                return ResourceManager.GetString("MlcbDesc_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Event raised when value of the FormatInfo property changes. 的本地化字符串。
        /// </summary>
        internal static string MlcbDesc_FormatInfoChanged {
            get {
                return ResourceManager.GetString("MlcbDesc_FormatInfoChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The format-specifier charactors that indicate how a value is to be displayed. 的本地化字符串。
        /// </summary>
        internal static string MlcbDesc_FormatString {
            get {
                return ResourceManager.GetString("MlcbDesc_FormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Event raised when value of the FormatString property changes. 的本地化字符串。
        /// </summary>
        internal static string MlcbDesc_FormatStringChanged {
            get {
                return ResourceManager.GetString("MlcbDesc_FormatStringChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A value indicating whether formatting is applied to the DisplayMember property of the combo box. 的本地化字符串。
        /// </summary>
        internal static string MlcbDesc_FormattingEnabled {
            get {
                return ResourceManager.GetString("MlcbDesc_FormattingEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Event raised when value of the FormattingEnabled property changes. 的本地化字符串。
        /// </summary>
        internal static string MlcbDesc_FormattingEnabledChanged {
            get {
                return ResourceManager.GetString("MlcbDesc_FormattingEnabledChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The height, in pixels, of an item in the combo box. 的本地化字符串。
        /// </summary>
        internal static string MlcbDesc_ItemHeight {
            get {
                return ResourceManager.GetString("MlcbDesc_ItemHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An object representing the collection of the items contained in the combo box. 的本地化字符串。
        /// </summary>
        internal static string MlcbDesc_Items {
            get {
                return ResourceManager.GetString("MlcbDesc_Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The maximum number of items to be shown in the drop-down portion of the combo box. 的本地化字符串。
        /// </summary>
        internal static string MlcbDesc_MaxDropDownItems {
            get {
                return ResourceManager.GetString("MlcbDesc_MaxDropDownItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The number of characters a user can type in to the combo box 的本地化字符串。
        /// </summary>
        internal static string MlcbDesc_MaxLength {
            get {
                return ResourceManager.GetString("MlcbDesc_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The prefeerred height of the combo box. 的本地化字符串。
        /// </summary>
        internal static string MlcbDesc_PreferredHeight {
            get {
                return ResourceManager.GetString("MlcbDesc_PreferredHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A value indicationg whether the editable portion of the combo box can be changed. 的本地化字符串。
        /// </summary>
        internal static string MlcbDesc_ReadOnly {
            get {
                return ResourceManager.GetString("MlcbDesc_ReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Currentry selected item in the combo box. 的本地化字符串。
        /// </summary>
        internal static string MlcbDesc_SelectedIndex {
            get {
                return ResourceManager.GetString("MlcbDesc_SelectedIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Event raised when the SelectedIndex property has changed. 的本地化字符串。
        /// </summary>
        internal static string MlcbDesc_SelectedIndexChanged {
            get {
                return ResourceManager.GetString("MlcbDesc_SelectedIndexChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Event raised when the SelectedValue property changes. 的本地化字符串。
        /// </summary>
        internal static string MlcbDesc_SelectedValueChanged {
            get {
                return ResourceManager.GetString("MlcbDesc_SelectedValueChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Event raised when the selected item has changed and that changes is displayed in the combo box. 的本地化字符串。
        /// </summary>
        internal static string MlcbDesc_SelectionChangeCommitted {
            get {
                return ResourceManager.GetString("MlcbDesc_SelectionChangeCommitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A value indicating whether the defined shortcuts are enabled. 的本地化字符串。
        /// </summary>
        internal static string MlcbDesc_ShortcutsEnabled {
            get {
                return ResourceManager.GetString("MlcbDesc_ShortcutsEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A value indicating whether a tooltip will be shown when a mouse cursor on the long text item in the drop-down portion of this combobox. 的本地化字符串。
        /// </summary>
        internal static string MlcbDesc_ShowDropDownToolTip {
            get {
                return ResourceManager.GetString("MlcbDesc_ShowDropDownToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A value indicating whether the sliding drop-down animation of the combo box is enabled. 的本地化字符串。
        /// </summary>
        internal static string MlcbDesc_SlidingDropDown {
            get {
                return ResourceManager.GetString("MlcbDesc_SlidingDropDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A value indicating whether the items in the combo box are sorted. 的本地化字符串。
        /// </summary>
        internal static string MlcbDesc_Sorted {
            get {
                return ResourceManager.GetString("MlcbDesc_Sorted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The appearance of the combo box. 的本地化字符串。
        /// </summary>
        internal static string MlcbDesc_Style {
            get {
                return ResourceManager.GetString("MlcbDesc_Style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Indicates how text is aligned in the editable portion of the combo box. 的本地化字符串。
        /// </summary>
        internal static string MlcbDesc_TextAlign {
            get {
                return ResourceManager.GetString("MlcbDesc_TextAlign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Event raised when the TextAlign property changes. 的本地化字符串。
        /// </summary>
        internal static string MlcbDesc_TextAlignChanged {
            get {
                return ResourceManager.GetString("MlcbDesc_TextAlignChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Indicates how text is aligned in the editable portion of the combo box.This property works only when the DropDownStyle property is the DropDownList. 的本地化字符串。
        /// </summary>
        internal static string MlcbDesc_TextVerticalAlign {
            get {
                return ResourceManager.GetString("MlcbDesc_TextVerticalAlign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The Property to use as the actual value for the items in the combo box. 的本地化字符串。
        /// </summary>
        internal static string MlcbDesc_ValueMember {
            get {
                return ResourceManager.GetString("MlcbDesc_ValueMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Event raised when the ValueMember property changes. 的本地化字符串。
        /// </summary>
        internal static string MlcbDesc_ValueMemberChanged {
            get {
                return ResourceManager.GetString("MlcbDesc_ValueMemberChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Indicates whether the editable portion  automatically wraps words to the beginning of the next line when necessary. 的本地化字符串。
        /// </summary>
        internal static string MlcbDesc_WordWrap {
            get {
                return ResourceManager.GetString("MlcbDesc_WordWrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Couldn&apos;t find item &apos;{0}&apos;. type: {1}. 的本地化字符串。
        /// </summary>
        internal static string MlcbExpt_CntFindItem {
            get {
                return ResourceManager.GetString("MlcbExpt_CntFindItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Couldn&apos;t find value &apos;{0}&apos;. type: {1}. 的本地化字符串。
        /// </summary>
        internal static string MlcbExpt_CntFindValue {
            get {
                return ResourceManager.GetString("MlcbExpt_CntFindValue", resourceCulture);
            }
        }
    }
}
